//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQuanAn.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBILL
    {
        public int idbill { get; set; }
        public int idfood { get; set; }
        public Nullable<int> slOrder { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual FOOD FOOD { get; set; }
    }
}
